name = "VecchiaMLE"
uuid = "499233a1-c46f-47cc-ab67-5a37788e9870"
authors = ["Caleb Derrickson <calebderrickson@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
